# Generated by Django 5.2.5 on 2026-02-12 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year of enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_assigned',
            field=models.ForeignKey(help_text='Class the student is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, help_text='Date when student was enrolled'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', help_text='Current enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(help_text='Student being enrolled', limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'academic_year'], name='students_en_student_ee0b07_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_assigned', 'status'], name='students_en_class_a_8ae698_idx'),
        ),
    ]
