# Generated by Django 5.2.5 on 2026-04-16 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_attendance_created_at_alter_attendance_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of attendance')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], db_index=True, default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(help_text='Admin who recorded this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_teacher_attendance', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher whose attendance is being recorded', limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendance',
                'ordering': ['-date', 'teacher__username'],
                'indexes': [models.Index(fields=['date', 'status'], name='teachers_te_date_3494d3_idx'), models.Index(fields=['teacher', 'date'], name='teachers_te_teacher_7d043c_idx')],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
