# Generated by Django 5.2.5 on 2026-02-13 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateField(auto_now_add=True, help_text='Date when assignment was created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.academicyear')),
                ('class_assigned', models.ForeignKey(help_text='Class receiving instruction', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.class')),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned to teach this subject', limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching Assignment',
                'verbose_name_plural': 'Teaching Assignments',
                'ordering': ['academic_year', 'class_assigned', 'subject'],
                'indexes': [models.Index(fields=['teacher', 'academic_year'], name='academics_t_teacher_13f96b_idx'), models.Index(fields=['class_assigned', 'academic_year'], name='academics_t_class_a_1b0572_idx'), models.Index(fields=['subject', 'academic_year'], name='academics_t_subject_fb5f38_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'class_assigned', 'academic_year'), name='unique_teaching_assignment')],
            },
        ),
    ]
