# Generated by Django 5.2.5 on 2026-04-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
